name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a branch principal do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Compilar Angular
        run: npm run build -- --configuration=production --base-href /front-meufacilitador/

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/front-meufacilitador
