name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build --prod

      - name: Deploy to GitHub Pages
        run: |
          # Configura o Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Acessa o diretório de build do Angular
          cd dist/front-meufacilitador  # Substitua com o caminho correto do seu build

          # Inicializa o repositório Git
          git init
          git add -A
          git commit -m "Deploy to GitHub Pages"

          # Adiciona o repositório remoto (branch gh-pages)
          git remote add origin https://github.com/${{ github.repository }}.git

          # Push forçando o envio para o branch gh-pages
          git push --force origin master:gh-pages
